# This file is used by TravisCI to automatically build and test the code every time there is a commit
# The xcodebuild command builds the project and the xctool command runs the tests

os: osx
osx_image: xcode9.2
language: swift
xcode_project: Mind-Full\ Meals.xcodeproj
xcode_scheme: Mind-Full\ Meals
script: xcodebuild clean build -sdk iphonesimulator -project Mind-Full\ Meals.xcodeproj -scheme Mind-Full\ Meals CODE_SIGNING_REQUIRED=NO && xctool -project Mind-Full\ Meals.xcodeproj -scheme Mind-Full\ Meals run-tests
